version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dlsa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - dlsa-network
    volumes:
      - db-data:/var/lib/postgresql/data

  dlsa-api:
    image: ben0531/dlsa-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dlsa
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      CORS_ALLOWED_ORIGINS: http://localhost
    ports:
      - "5004:8080"
      - "5005:5005"
    depends_on:
      - db
    networks:
      - dlsa-network

  dlsa-app:
    image: ben0531/dlsa-app:latest
    ports:
      - "80:80"
    depends_on:
      - dlsa-api
    networks:
      - dlsa-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dlsa-network

networks:
  dlsa-network:
    driver: bridge

volumes:
  db-data: {}
