FROM maven:latest AS build
WORKDIR /build
COPY ./DlsaApi .
RUN mvn clean install "-DskipTests"

FROM openjdk:20
EXPOSE 8080
EXPOSE 3306
WORKDIR /app
COPY --from=build /build/target/DlsaApi-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java","-jar","DlsaApi-0.0.1-SNAPSHOT.jar"]
# /build/target/DlsaApi-0.0.1-SNAPSHOT.jar
